openai_api_key: "xxx" # optional
openai_host: "xx"  # optional
proxy: "http://127.0.0.1:7890"  # optional
redis:
  username: "user"
  password: "password123"
  host: "localhost"
  port: 6379
go_weekly:
  webhooks:
    - "http://example.com/webhook1"
    - "http://example.com/webhook2"
  cron_expression: "0 30 10 * * *"
  once_post_limit: 5
go_blog:
  webhooks:
    - "http://example.com/webhook1"
    - "http://example.com/webhook2"
  cron_expression: "0 30 10 * * *"
  once_post_limit: 1
rust_blog:
  webhooks:
    - "http://example.com/webhook1"
    - "http://example.com/webhook2"
  cron_expression: "0 30 10 * * *"
  once_post_limit: 2
redis_official_blog:
  webhooks:
    - "http://example.com/webhook1"
    - "http://example.com/webhook2"
  cron_expression: "0 30 10 * * *"
  once_post_limit: 1